config/routes.rb
Mne::Application.routes.draw do

  get "page/meetings"
  get "page/create_meet"
  get "page/profile"
  get "page/about_us"
  get "page/place"

  get "user/index"

  resource :lot, :except => [:show, :edit]
  get "lot/:id/edit" => "lots#edit"

  devise_for :users
  root :to => "page#meetings"
  

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :lot
  # attr_accessible :title, :body
end

app/models/lot.rb
class Lot < ActiveRecord::Base
  has_many :bid
  belongs_to :user
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :lots
  has_many :bids
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def meetings
    @meets = Lot.limit(3)
  end

  def create_meet
  end

  def profile
  end

  def about_us
  end

  def place
  end

  end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lot_helper.rb
module LotHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mne" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
<body>

    <div id="wrap">
        <%= render 'shared/menu' %>
        <div class="container">
            <div class="row">
                <div class="span9">
                    <%= bootstrap_flash %>
                    <%= yield %>
                </div>
            </div>
        </div>
        <div id="push"></div>
    </div>


    <%= render 'shared/footer' %>

</body>
</html>

app/views/lots/edit.html.erb
<h1>Lot#edit</h1>
<p>Find me in app/views/lot/edit.html.erb</p>

app/views/lots/new.html.erb
<h1>Lot#new</h1>
<p>Find me in app/views/lot/new.html.erb</p>

app/views/page/about_us.html.erb
<h1>Page#about_us</h1>
<p>Find me in app/views/page/about_us.html.erb</p>

app/views/page/create_meet.html.erb
<h1>Page#create_meet</h1>
<p>Find me in app/views/page/create_meet.html.erb</p>

app/views/page/meetings.html.erb
<h1>Page#meets</h1>
<p>Find me in app/views/page/meets.html.erb</p>
<div class="panel">
  <div class="title">Available meets:</div>
  <div class="content">
    <%  @meets.each do |meet| %>
        <div>
            <blockquote>
              ID=<%= meet.id %> (Owner <%= meet.user.first_name %>)
            </blockquote>
        </div>
    <% end %>
  </div>
</div>

app/views/page/place.html.erb
<h1>Page#place</h1>
<p>Find me in app/views/page/place.html.erb</p>

app/views/page/profile.html.erb
<h1>Page#profile</h1>
<p>Find me in app/views/page/profile.html.erb</p>

app/views/shared/_footer.html.erb
<div class="navbar navbar-fixed-bottom">
  <div class="container">
    <p>&copy; Company 2014</p>
  </div>
</div>

app/views/shared/_menu.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Mne</a>
      <div class="container nav-collapse">
        <ul class="nav">
          <% unless user_signed_in? %>
              <li><%= link_to "About us", page_about_us_path %></li>
          <% else %>
              <li><%= link_to "Meetings", page_meetings_path  %></li>
              <li><%= link_to "Place", page_place_path  %></li>
              <li><%= link_to "Create meeting", page_create_meet_path  %></li>
              <li><%= link_to "Profile", page_profile_path %></li>
          <% end %>
        </ul>
        <ul class="nav pull-right">
          <% unless user_signed_in? %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
          <% else %>
              <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
          <% end %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Language <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><a href="#">English</a></li>
              <li><a href="#">Русский</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/user/index.html.erb
<h1>Hello!!!</h1>

<% unless user_signed_in? %>
    <p><%= link_to 'Sign up as User', new_user_registration_path %></p>
    <p><%= link_to 'Sign in as User', new_user_session_path %></p>
<% else %>
    <p><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></p>
<% end %>
<p>Hello World!/</p>

<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>